<form id="shippinginsurance-form" action="">
    <fieldset>
        <?php if ($this->helper('shipping_insurance')->isNewStep() && $this->helper('shipping_insurance')->isEnabled()) {
            echo $this->getChildHtml('insurance.checkbox');
        }
        ?>
        <div class="buttons-set" id="shippinginsurance-buttons-container">
            <button type="button" title="<?php echo $this->__('Continue') ?>" class="button" onclick="shippinginsurance.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <span class="please-wait" id="shippinginsurance-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
    //<![CDATA[
    var shippinginsurance = new ShippingInsurance('shippinginsurance-form','<?php echo $this->getUrl('checkout/onepage/saveShippingInsurance') ?>');
    var ShippingInsuranceForm = new VarienForm('shippinginsurance-form');
    //]]>
</script>